version: '3.3'

services:
  server:
    container_name: node-digichlist-api
    restart: always
    build: .
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://docdb-digichlist.cluster-ckcyrr90b8e5.us-east-1.docdb.amazonaws.com:27017/app
      - JWT=text

